#!/usr/bin/env bash
echo "== deploy s3 bucket via CFN"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region ap-northeast-2 \
--stack-name $STACK_NAME \